const abi = [
    {
      inputs: [
        {
          internalType: "address",
          name: "_originalSpotlightContract",
          type: "address",
        },
        { internalType: "uint256", name: "_protocolStartTime", type: "uint256" },
        { internalType: "address", name: "_protocolWallet", type: "address" },
        { internalType: "address", name: "_protocolSigner", type: "address" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    { inputs: [], name: "ECDSAInvalidSignature", type: "error" },
    {
      inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
      name: "ECDSAInvalidSignatureLength",
      type: "error",
    },
    {
      inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }],
      name: "ECDSAInvalidSignatureS",
      type: "error",
    },
    { inputs: [], name: "FidAlreadyLinked", type: "error" },
    { inputs: [], name: "InsufficientPayment", type: "error" },
    { inputs: [], name: "InvalidDay", type: "error" },
    { inputs: [], name: "InvalidSender", type: "error" },
    { inputs: [], name: "InvalidSignature", type: "error" },
    { inputs: [], name: "NonexistentUser", type: "error" },
    {
      inputs: [{ internalType: "address", name: "owner", type: "address" }],
      name: "OwnableInvalidOwner",
      type: "error",
    },
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "OwnableUnauthorizedAccount",
      type: "error",
    },
    { inputs: [], name: "RemovePeriodElapsed", type: "error" },
    { inputs: [], name: "SpotlightAvailable", type: "error" },
    { inputs: [], name: "SpotlightUnavailable", type: "error" },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "uint256",
          name: "spotlightOwnerFid",
          type: "uint256",
        },
        {
          indexed: true,
          internalType: "uint256",
          name: "spotlightBookerFid",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "boostAmount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "newPriceIndex",
          type: "uint256",
        },
      ],
      name: "BoostRecorded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: "uint256", name: "fid", type: "uint256" },
        {
          indexed: true,
          internalType: "address",
          name: "newWallet",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "oldWallet",
          type: "address",
        },
      ],
      name: "FidTransfer",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: "uint256", name: "fid", type: "uint256" },
        {
          indexed: true,
          internalType: "address",
          name: "wallet",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "earningsClaimed",
          type: "uint256",
        },
      ],
      name: "LinkAndClaim",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "oldSigner",
          type: "address",
        },
        {
          indexed: false,
          internalType: "address",
          name: "newSigner",
          type: "address",
        },
      ],
      name: "ProtocolSignerSet",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "oldWallet",
          type: "address",
        },
        {
          indexed: false,
          internalType: "address",
          name: "newWallet",
          type: "address",
        },
      ],
      name: "ProtocolWalletSet",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "uint256",
          name: "spotlightOwnerFid",
          type: "uint256",
        },
        {
          indexed: true,
          internalType: "uint256",
          name: "spotlightBookerFid",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "sequentialDay",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "price",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "string",
          name: "contentUri",
          type: "string",
        },
        {
          indexed: true,
          internalType: "string",
          name: "dataKey",
          type: "string",
        },
      ],
      name: "SpotlightBooked",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "uint256",
          name: "spotlightOwnerFid",
          type: "uint256",
        },
        {
          indexed: true,
          internalType: "uint256",
          name: "spotlightBookerFid",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "sequentialDay",
          type: "uint256",
        },
      ],
      name: "SpotlightBookingRemoved",
      type: "event",
    },
    {
      inputs: [],
      name: "BOOST",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "DAY_7_BOOST",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "DECAY_FACTOR",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "FEE_DIVISOR",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "MIN_BOOKING_FEE",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "MIN_BOOKING_RANGE",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "MIN_BOOST_DIVISOR",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "ONE_DAY",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "ONE_WEEK",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "spotlightOwnerFid", type: "uint256" },
        { internalType: "uint256", name: "day", type: "uint256" },
        { internalType: "string", name: "contentUri", type: "string" },
        { internalType: "string", name: "nonce", type: "string" },
        { internalType: "bytes", name: "signature", type: "bytes" },
        { internalType: "string", name: "dataKey", type: "string" },
      ],
      name: "bookSpotlight",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "spotlightOwnerFid", type: "uint256" },
        { internalType: "string", name: "contentUri", type: "string" },
        { internalType: "string", name: "nonce", type: "string" },
        { internalType: "bytes", name: "signature", type: "bytes" },
        { internalType: "string", name: "dataKey", type: "string" },
      ],
      name: "bookSpotlightMinPrice",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "fid", type: "uint256" }],
      name: "getAddressByFid",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "fid", type: "uint256" }],
      name: "getAddressByFidSafe",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getBasePriceIndex",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "fid", type: "uint256" }],
      name: "getClaimableEarnings",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getCurrentDayStartAndEnd",
      outputs: [
        { internalType: "uint256", name: "start", type: "uint256" },
        { internalType: "uint256", name: "end", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getCurrentSequentialDayNumber",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "spotlightOwnerFid", type: "uint256" },
      ],
      name: "getEarliestAvailableDayAndPrice",
      outputs: [
        { internalType: "uint256", name: "day", type: "uint256" },
        { internalType: "uint256", name: "price", type: "uint256" },
        { internalType: "bool", name: "isAvailable", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "wallet", type: "address" }],
      name: "getFidByAddress",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "spotlightOwnerFid", type: "uint256" },
        { internalType: "uint256", name: "sequentialDay", type: "uint256" },
      ],
      name: "getRefundAmount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "spotlightOwnerFid", type: "uint256" },
        { internalType: "uint256", name: "sequentialDay", type: "uint256" },
      ],
      name: "getSpotlightBooking",
      outputs: [
        {
          components: [
            { internalType: "bool", name: "booked", type: "bool" },
            { internalType: "uint256", name: "bookerFid", type: "uint256" },
            { internalType: "uint256", name: "bookedTimestamp", type: "uint256" },
            { internalType: "uint256", name: "price", type: "uint256" },
            { internalType: "string", name: "contentUri", type: "string" },
          ],
          internalType: "struct SpotlightProtocolV1.SpotlightBooking",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "spotlightOwnerFid", type: "uint256" },
        { internalType: "uint256", name: "day", type: "uint256" },
      ],
      name: "getSpotlightBookingByDay",
      outputs: [
        {
          components: [
            { internalType: "bool", name: "booked", type: "bool" },
            { internalType: "uint256", name: "bookerFid", type: "uint256" },
            { internalType: "uint256", name: "bookedTimestamp", type: "uint256" },
            { internalType: "uint256", name: "price", type: "uint256" },
            { internalType: "string", name: "contentUri", type: "string" },
          ],
          internalType: "struct SpotlightProtocolV1.SpotlightBooking",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "spotlightOwnerFid", type: "uint256" },
        { internalType: "uint256", name: "day", type: "uint256" },
      ],
      name: "getSpotlightPrice",
      outputs: [{ internalType: "uint256", name: "price", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "spotlightOwnerFid", type: "uint256" },
        { internalType: "uint256", name: "day", type: "uint256" },
      ],
      name: "isSpotlightBooked",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "fid", type: "uint256" },
        { internalType: "address", name: "wallet", type: "address" },
        { internalType: "bytes", name: "signature", type: "bytes" },
      ],
      name: "linkAndClaim",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "protocolSigner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "protocolStartTime",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "protocolWallet",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "sequentialDay", type: "uint256" },
      ],
      name: "removeBookedSpotlight",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newSigner", type: "address" }],
      name: "setProtocolSigner",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newWallet", type: "address" }],
      name: "setProtocolWallet",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferFidOwner",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ] as any;
  
  export default abi;
  